# Generated by Django 5.2.8 on 2026-05-10 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooman_alytics', '0001_room_analytics_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnnxModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя файла модели', max_length=255)),
                ('category', models.CharField(choices=[('detection', 'Детекция комнат и стен'), ('classification', 'Классификация комнат'), ('furniture', 'Детекция и классификация мебели')], db_index=True, help_text='Категория модели', max_length=50)),
                ('onnx_file', models.FileField(help_text='ONNX файл модели', upload_to='C:\\ergo_ms\\ergo_ms_core\\modules\\Rooman_alytics/api/models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['onnx'])])),
                ('classes', models.JSONField(default=list, help_text="Список обнаруживаемых классов: ['sofa', 'table', ...]")),
                ('install_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Используется ли модель на сервере прямо сейчас')),
            ],
            options={
                'ordering': ['-install_date'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='rooman_alyt_categor_470df7_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'category'), name='unique_name_per_category')],
            },
        ),
    ]
