# Generated by Django 5.2.8 on 2026-05-10 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onnxmodel',
            name='onnx_file',
            field=models.FileField(help_text='ONNX файл модели', upload_to='rooman_alytics/models/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['onnx'])]),
        ),
    ]
