# Generated by Django 5.2.8 on 2026-05-21 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0005_roomanalyticspluginstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion_of_ergonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_creation', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('weight', models.FloatField(default=0, verbose_name='Вес')),
                ('color', models.CharField(default='#0d6efd', max_length=7, verbose_name='Цвет')),
                ('terrible_mark_high', models.FloatField(default=3)),
                ('bad_mark_low', models.FloatField(default=5)),
                ('normal_mark_low', models.FloatField(default=7)),
                ('good_mark_low', models.FloatField(default=9)),
                ('excellent_mark_high', models.FloatField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Form_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesion', models.TextField()),
                ('type', models.CharField(choices=[('for_every_room', 'Для каждой комнаты'), ('for_floorplan', 'Для каждого помещения')], db_index=True, help_text='Категория модели', max_length=50)),
                ('criterion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.criterion_of_ergonomy')),
            ],
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('Score', models.FloatField(default=5)),
                ('qusion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.form_question')),
            ],
        ),
    ]
