# Generated by Django 5.2.8 on 2026-05-21 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0006_criterion_of_ergonomy_form_question_formanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructElementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#0d6efd', max_length=7, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Floorplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(help_text='планы изображений', upload_to='floorplans', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.png', 'jpg'])])),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#0d6efd', max_length=7, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#0d6efd', max_length=7, verbose_name='Цвет')),
            ],
        ),
        migrations.AddField(
            model_name='criterion_of_ergonomy',
            name='bad_mark_high',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='criterion_of_ergonomy',
            name='good_mark_high',
            field=models.FloatField(default=9),
        ),
        migrations.AddField(
            model_name='criterion_of_ergonomy',
            name='normal_mark_high',
            field=models.FloatField(default=7),
        ),
        migrations.AlterField(
            model_name='criterion_of_ergonomy',
            name='bad_mark_low',
            field=models.FloatField(default=3.1),
        ),
        migrations.AlterField(
            model_name='criterion_of_ergonomy',
            name='good_mark_low',
            field=models.FloatField(default=7.1),
        ),
        migrations.AlterField(
            model_name='criterion_of_ergonomy',
            name='normal_mark_low',
            field=models.FloatField(default=5.1),
        ),
    ]
