# Generated by Django 5.2.8 on 2026-05-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0007_constructelementtype_floorplan_furnituretype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion_of_ergonomy',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
