# Generated by Django 5.2.8 on 2026-05-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0008_alter_criterion_of_ergonomy_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterion_of_ergonomy',
            name='excellent_mark_high',
        ),
        migrations.AddField(
            model_name='criterion_of_ergonomy',
            name='excellent_mark_low',
            field=models.FloatField(default=9),
        ),
        migrations.AlterField(
            model_name='criterion_of_ergonomy',
            name='good_mark_high',
            field=models.FloatField(default=8),
        ),
    ]
