# Generated by Django 5.2.8 on 2026-05-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0009_remove_criterion_of_ergonomy_excellent_mark_high_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criterion_of_ergonomy',
            old_name='bad_mark_high',
            new_name='bad_mark_border',
        ),
        migrations.RenameField(
            model_name='criterion_of_ergonomy',
            old_name='good_mark_high',
            new_name='good_mark_border',
        ),
        migrations.RenameField(
            model_name='criterion_of_ergonomy',
            old_name='normal_mark_high',
            new_name='normal_mark_border',
        ),
        migrations.RenameField(
            model_name='criterion_of_ergonomy',
            old_name='terrible_mark_high',
            new_name='terrible_mark_border',
        ),
        migrations.RemoveField(
            model_name='criterion_of_ergonomy',
            name='bad_mark_low',
        ),
        migrations.RemoveField(
            model_name='criterion_of_ergonomy',
            name='excellent_mark_low',
        ),
        migrations.RemoveField(
            model_name='criterion_of_ergonomy',
            name='good_mark_low',
        ),
        migrations.RemoveField(
            model_name='criterion_of_ergonomy',
            name='normal_mark_low',
        ),
    ]
