# Generated by Django 5.2.8 on 2026-05-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0010_rename_bad_mark_high_criterion_of_ergonomy_bad_mark_border_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructelementtype',
            name='label',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='furnituretype',
            name='label',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='label',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='criterion_of_ergonomy',
            name='good_mark_border',
            field=models.FloatField(default=9),
        ),
    ]
