# Generated by Django 5.2.8 on 2026-05-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0011_constructelementtype_label_furnituretype_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_question',
            name='type',
            field=models.CharField(choices=[('for_every_room', 'Для каждой комнаты'), ('for_floorplan', 'Для каждого помещения'), ('for_selected_rooms', 'для выбранных комнат'), ('for_unselected_rooms', 'для невыбранных комнат')], db_index=True, help_text='Категория модели', max_length=50),
        ),
    ]
