# Generated by Django 5.2.8 on 2026-05-21 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0012_alter_form_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Question_RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qusion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.form_question')),
                ('room_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.roomtype')),
            ],
            options={
                'unique_together': {('qusion_id', 'room_type_id')},
            },
        ),
    ]
