# Generated by Django 5.2.8 on 2026-05-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0013_form_question_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_question',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
