# Generated by Django 5.2.8 on 2026-05-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0014_form_question_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_question',
            name='recomendation',
            field=models.TextField(default=''),
        ),
    ]
