# Generated by Django 5.2.8 on 2026-05-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0015_form_question_recomendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_question',
            old_name='quesion',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='form_question',
            old_name='recomendation',
            new_name='recommendation',
        ),
        migrations.RenameField(
            model_name='formanswer',
            old_name='qusion_id',
            new_name='qustion_id',
        ),
        migrations.RenameField(
            model_name='formanswer',
            old_name='Score',
            new_name='score',
        ),
        migrations.AddField(
            model_name='form_question',
            name='score_for_recommendation',
            field=models.FloatField(default=6),
        ),
    ]
