# Generated by Django 5.2.8 on 2026-05-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0016_rename_quesion_form_question_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formanswer',
            old_name='qustion_id',
            new_name='question_id',
        ),
    ]
