# Generated by Django 5.2.8 on 2026-05-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0017_rename_qustion_id_formanswer_question_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionElementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#0d6efd', max_length=7, verbose_name='Цвет')),
                ('label', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
