# Generated by Django 5.2.8 on 2026-05-22 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0018_constructionelementtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_x', models.FloatField(default=0)),
                ('max_x', models.FloatField(default=0)),
                ('min_y', models.FloatField(default=0)),
                ('max_y', models.FloatField(default=0)),
                ('construct_element_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.constructelementtype')),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_x', models.FloatField(default=0)),
                ('max_x', models.FloatField(default=0)),
                ('min_y', models.FloatField(default=0)),
                ('max_y', models.FloatField(default=0)),
                ('furniture_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.furnituretype')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_x', models.FloatField(default=0)),
                ('max_x', models.FloatField(default=0)),
                ('min_y', models.FloatField(default=0)),
                ('max_y', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='ConstructionElementType',
        ),
        migrations.AddField(
            model_name='floorplan',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='pixel_to_m_in_square',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='square_of_habitation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='upload_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Загружен'),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='width',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='constructelement',
            name='floorplan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.floorplan'),
        ),
        migrations.AddField(
            model_name='room',
            name='floorplan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.floorplan'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.roomtype'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='room_firts_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.room'),
        ),
        migrations.AddField(
            model_name='constructelement',
            name='room_firts_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construct_elements_as_first', to='rooman_alytics.room'),
        ),
        migrations.AddField(
            model_name='constructelement',
            name='room_second_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construct_elements_as_second', to='rooman_alytics.room'),
        ),
    ]
