# Generated by Django 5.2.8 on 2026-05-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0019_constructelement_furniture_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furniture',
            old_name='room_firts_id',
            new_name='room_id',
        ),
        migrations.RemoveField(
            model_name='constructelement',
            name='room_firts_id',
        ),
        migrations.RemoveField(
            model_name='constructelement',
            name='room_second_id',
        ),
    ]
