# Generated by Django 5.2.8 on 2026-05-23 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0020_rename_room_firts_id_furniture_room_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='square',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='img',
            field=models.FileField(help_text='план изображений', upload_to='floorplans', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.png', 'jpg'])]),
        ),
    ]
