# Generated by Django 5.2.8 on 2026-05-24 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0021_room_square_alter_floorplan_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCountingParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecialMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inputType', models.CharField(choices=[('nothing', 'Nothing'), ('rooms', 'Rooms'), ('furniture', 'Furniture'), ('roomsfurniture', 'Rooms Furniture')], default='nothing', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SystemEquastion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SystemEquastionForRooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ACPUsings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture_type', models.ForeignKey(db_column='furniture_type_id', on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.furnituretype')),
                ('room_type', models.ForeignKey(db_column='room_type_id', on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.roomtype')),
                ('acp', models.ForeignKey(db_column='acp_id', on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.autocountingparam')),
            ],
        ),
        migrations.CreateModel(
            name='CommonFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('value_recomm_type', models.CharField(blank=True, choices=[('min', 'Minimum'), ('max', 'Maximum')], max_length=10, null=True)),
                ('value_recomm', models.FloatField(blank=True, null=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.formula')),
            ],
        ),
        migrations.CreateModel(
            name='FormulaParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('cryteria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.criterion_of_ergonomy')),
            ],
        ),
        migrations.AddField(
            model_name='autocountingparam',
            name='formula_param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.formulaparam'),
        ),
        migrations.CreateModel(
            name='FormuleAcp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.autocountingparam')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.formula')),
            ],
        ),
        migrations.CreateModel(
            name='LimitParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_param', models.ForeignKey(db_column='FormulaParamId', on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.formulaparam')),
            ],
        ),
        migrations.CreateModel(
            name='RoomsLimitParam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('limit_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.limitparam')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.roomtype')),
            ],
        ),
        migrations.AddField(
            model_name='autocountingparam',
            name='special_methods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.specialmethods'),
        ),
        migrations.CreateModel(
            name='RoomsSysEq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.formula')),
                ('rooms_limit_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.roomslimitparam')),
                ('system_equastion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.systemequastion')),
            ],
        ),
        migrations.CreateModel(
            name='SysEquastRoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.roomtype')),
                ('sys_eq_rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.systemequastionforrooms')),
            ],
        ),
        migrations.CreateModel(
            name='UniversalLimitParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('limit_param', models.ForeignKey(db_column='LimitParamId', on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.limitparam')),
            ],
        ),
        migrations.CreateModel(
            name='UniversalSysEq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.formula')),
                ('system_equastion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.systemequastion')),
                ('universal_limit_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.universallimitparam')),
            ],
        ),
        migrations.CreateModel(
            name='UserInputParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('formula_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.formulaparam')),
            ],
        ),
        migrations.CreateModel(
            name='FormulaUserInputParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.formula')),
                ('user_input_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.userinputparam')),
            ],
        ),
    ]
