# Generated by Django 5.2.8 on 2026-05-25 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0022_autocountingparam_formula_specialmethods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinputparam',
            name='type',
            field=models.CharField(choices=[('global', 'Global'), ('rooms', 'Rooms')], default='global', max_length=50),
        ),
        migrations.CreateModel(
            name='UserInputParamRoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.roomtype')),
                ('user_input_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.userinputparam')),
            ],
        ),
    ]
