# Generated by Django 5.2.8 on 2026-05-25 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0023_userinputparam_type_userinputparamroomtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='formulaparam',
            name='cryteria_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.criterion_of_ergonomy'),
        ),
    ]
