# Generated by Django 5.2.8 on 2026-05-25 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0024_alter_formula_id_alter_formulaparam_cryteria_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acpusings',
            name='acp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.autocountingparam'),
        ),
        migrations.AlterField(
            model_name='acpusings',
            name='furniture_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.furnituretype'),
        ),
        migrations.AlterField(
            model_name='acpusings',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.roomtype'),
        ),
    ]
