# Generated by Django 5.2.8 on 2026-05-25 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0025_alter_acpusings_acp_alter_acpusings_furniture_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormuleAcp',
            new_name='FormulaAcp',
        ),
        migrations.RemoveField(
            model_name='sysequastroomtype',
            name='sys_eq_rooms',
        ),
        migrations.RemoveField(
            model_name='commonformula',
            name='value_recomm_type',
        ),
        migrations.AddField(
            model_name='commonformula',
            name='type',
            field=models.CharField(choices=[('global', 'Global'), ('rooms', 'Rooms')], default='global', max_length=50),
        ),
        migrations.AddField(
            model_name='sysequastroomtype',
            name='system_equastion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.systemequastion'),
        ),
        migrations.AlterField(
            model_name='formula',
            name='equation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='roomslimitparam',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roomssyseq',
            name='system_equastion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.systemequastion'),
        ),
        migrations.AlterField(
            model_name='systemequastion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CommonFormulaRoomTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commonformula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.commonformula')),
                ('roomtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.roomtype')),
            ],
        ),
        migrations.DeleteModel(
            name='SystemEquastionForRooms',
        ),
    ]
