# Generated by Django 5.2.8 on 2026-05-26 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0026_rename_formuleacp_formulaacp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulauserinputparam',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='formulauserinputparam',
            name='user_input_param',
        ),
        migrations.RemoveField(
            model_name='sysequastroomtype',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='sysequastroomtype',
            name='system_equastion',
        ),
        migrations.RemoveField(
            model_name='roomssyseq',
            name='rooms_limit_param',
        ),
        migrations.RemoveField(
            model_name='universalsyseq',
            name='universal_limit_param',
        ),
        migrations.AlterField(
            model_name='commonformularoomtypes',
            name='commonformula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.commonformula'),
        ),
        migrations.CreateModel(
            name='CommonFormulaAcp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.autocountingparam')),
                ('commonformula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.commonformula')),
            ],
        ),
        migrations.CreateModel(
            name='CommonFormulaInputParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commonformula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.commonformula')),
                ('user_input_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.userinputparam')),
            ],
        ),
        migrations.CreateModel(
            name='RoomSysEqRoomRoomsLimitParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_system_equastion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.roomssyseq')),
                ('rooms_limit_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.roomslimitparam')),
            ],
        ),
        migrations.CreateModel(
            name='RoomSysEquastRoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_system_equastion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.roomssyseq')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='SystemEquastionUserACP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.autocountingparam')),
                ('sys_equ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.systemequastion')),
            ],
        ),
        migrations.CreateModel(
            name='SystemEquastionUserInputParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_equ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.systemequastion')),
                ('useR_input_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.userinputparam')),
            ],
        ),
        migrations.CreateModel(
            name='UniversalSysEqUniversalLimitParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universal_limit_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.universallimitparam')),
                ('universal_sys_equastion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.universalsyseq')),
            ],
        ),
        migrations.DeleteModel(
            name='FormulaAcp',
        ),
        migrations.DeleteModel(
            name='FormulaUserInputParam',
        ),
        migrations.DeleteModel(
            name='SysEquastRoomType',
        ),
    ]
