# Generated by Django 5.2.8 on 2026-05-27 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0027_remove_formulauserinputparam_formula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomsysequastroomtype',
            name='room_system_equastion',
        ),
        migrations.RemoveField(
            model_name='roomsysequastroomtype',
            name='room_type',
        ),
        migrations.AddField(
            model_name='systemequastion',
            name='type',
            field=models.CharField(choices=[('house', 'House'), ('rooms', 'Rooms')], default='house', max_length=50),
        ),
        migrations.CreateModel(
            name='SysEquastRoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.roomtype')),
                ('system_equastion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.systemequastion')),
            ],
        ),
        migrations.CreateModel(
            name='SystemEquastionRoomRoomsLimitParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_system_equastion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.systemequastion')),
                ('rooms_limit_param', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.roomslimitparam')),
            ],
        ),
        migrations.DeleteModel(
            name='RoomSysEqRoomRoomsLimitParam',
        ),
        migrations.DeleteModel(
            name='RoomSysEquastRoomType',
        ),
    ]
