# Generated by Django 5.2.8 on 2026-05-27 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0028_remove_roomsysequastroomtype_room_system_equastion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemequastionroomroomslimitparam',
            old_name='room_system_equastion',
            new_name='system_equastion',
        ),
        migrations.CreateModel(
            name='SystemEquastionUniversalLimitParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_equastion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.systemequastion')),
                ('universal_limit_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.universallimitparam')),
            ],
        ),
        migrations.DeleteModel(
            name='UniversalSysEqUniversalLimitParam',
        ),
    ]
