# Generated by Django 5.2.8 on 2026-05-27 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0029_rename_room_system_equastion_systemequastionroomroomslimitparam_system_equastion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acpusings',
            name='furniture_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.furnituretype'),
        ),
        migrations.AlterField(
            model_name='acpusings',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.roomtype'),
        ),
        migrations.AlterField(
            model_name='commonformula',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='commonformula',
            name='value_recomm',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='commonformulaacp',
            name='acp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.autocountingparam'),
        ),
        migrations.AlterField(
            model_name='commonformulaacp',
            name='commonformula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.commonformula'),
        ),
        migrations.AlterField(
            model_name='commonformulainputparam',
            name='commonformula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.commonformula'),
        ),
        migrations.AlterField(
            model_name='commonformularoomtypes',
            name='commonformula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.commonformula'),
        ),
        migrations.AlterField(
            model_name='roomssyseq',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='roomssyseq',
            name='system_equastion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.systemequastion'),
        ),
        migrations.AlterField(
            model_name='sysequastroomtype',
            name='system_equastion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.systemequastion'),
        ),
        migrations.AlterField(
            model_name='systemequastionroomroomslimitparam',
            name='system_equastion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.systemequastion'),
        ),
        migrations.AlterField(
            model_name='systemequastionuniversallimitparam',
            name='sys_equastion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.systemequastion'),
        ),
        migrations.AlterField(
            model_name='systemequastionuseracp',
            name='acp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.autocountingparam'),
        ),
        migrations.AlterField(
            model_name='universalsyseq',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
    ]
