# Generated by Django 5.2.8 on 2026-05-27 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0030_alter_acpusings_furniture_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemEquastionRoomRoomsLimitParam',
            new_name='SystemEquastionRoomsLimitParam',
        ),
        migrations.RemoveField(
            model_name='universalsyseq',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='universalsyseq',
            name='system_equastion',
        ),
        migrations.AddField(
            model_name='commonformula',
            name='criterion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.criterion_of_ergonomy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemequastion',
            name='criterion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.criterion_of_ergonomy'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EquastionOfSystemEquastion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_equastion', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.formula')),
                ('system_equastion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.systemequastion')),
            ],
        ),
        migrations.DeleteModel(
            name='RoomsSysEq',
        ),
        migrations.DeleteModel(
            name='UniversalSysEq',
        ),
    ]
