# Generated by Django 5.2.8 on 2026-05-27 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0031_rename_systemequastionroomroomslimitparam_systemequastionroomslimitparam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonformula',
            name='criterion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.criterion_of_ergonomy'),
        ),
        migrations.AlterField(
            model_name='systemequastion',
            name='criterion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.criterion_of_ergonomy'),
        ),
    ]
