# Generated by Django 5.2.8 on 2026-06-03 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0033_alter_acpusings_furniture_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCountingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=40)),
                ('inputType', models.CharField(choices=[('nothing', 'Nothing'), ('rooms', 'Rooms'), ('furniture', 'Furniture'), ('roomsfurniture', 'Rooms Furniture')], default='nothing', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='commonformula',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='criterion_of_ergonomy',
            name='is_counting_by_system_equastion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='criterion_of_ergonomy',
            name='var_name',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='formulaparam',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemequastion',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AutoCountingMethod_Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_counting_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.autocountingmethod')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.criterion_of_ergonomy')),
            ],
        ),
        migrations.CreateModel(
            name='SystemEquastionForCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.criterion_of_ergonomy')),
            ],
        ),
        migrations.CreateModel(
            name='EquastionOfCriterionSystemEquastion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_equastion', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.formula')),
                ('criterion_system_equastion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.systemequastionforcriterion')),
            ],
        ),
        migrations.CreateModel(
            name='CilterionUsingForFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.criterion_of_ergonomy')),
                ('system_equation_for_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooman_alytics.systemequastionforcriterion')),
            ],
        ),
        migrations.CreateModel(
            name='SystemEquastionForCriterion_UIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_equation_for_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_params', to='rooman_alytics.systemequastionforcriterion')),
                ('user_input_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_equation_bindings', to='rooman_alytics.userinputparam')),
            ],
        ),
    ]
