# Generated by Django 5.2.8 on 2026-06-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooman_alytics', '0035_delete_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonformula',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='systemequastion',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
