# Generated by Django 5.2.8 on 2026-05-10 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_ergonomics', '0006_analytics_mvp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='equipmentmetricbycountry',
            new_name='equipment_e_country_bc629b_idx',
            old_name='equipment_er_country_8b0f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentmetricbycountry',
            new_name='equipment_e_equipme_105c85_idx',
            old_name='equipment_er_equipme_2a8c2a_idx',
        ),
    ]
